import numpy as np
import cv2
import random

# Load an color image in grayscale
img = cv2.imread("images/map1.png",-1)
print(img[0][0])
grey = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
mask = cv2.inRange(grey, 10, 200);
_, cnts, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)

drawn = np.zeros((img.shape[0], img.shape[1], 4))

pointer = open("pointer.js", "w")
pointer.write("")
pointer.close()
pointer = open("pointer.js", "a")
pointer.write("//generated by script\nvar countryImgs = [];\n")

if len(cnts) >= 1:
	countries = [];
	for current_contour in cnts:
		if cv2.contourArea(current_contour) > 50:
			countries.append(current_contour)
	for i in range(len(countries)):
		cv2.drawContours(drawn, countries, i, (random.random(), random.random(), random.random(), 1), 3)

		countryImg = np.ones((img.shape[0], img.shape[1], 4))
		cv2.drawContours(countryImg, countries, i, (0, 0, 0, 0.5), 5)
		cv2.imwrite("images/country"+str(i)+".png", countryImg);
		pointer.write("countryImgs.push(new SingleImage('images/country"+str(i)+".png'));\n");
		print("countryImgs.push(new SingleImage('images/country"+str(i)+".png'));")
pointer.close()
#cv2.imwrite("images/everything")
cv2.imshow('test',cv2.resize(drawn, (800, 600)))
cv2.waitKey(0)
cv2.destroyAllWindows()